name: Solar system
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - feature/*
env:
    MONGO_URI: ${{ vars.MONGO_URI }}
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    unit_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - name: Install dependencies
              run: npm install
            
            - name: Run unit tests
              run: npm test
            